### ISSUE TITLE
Oz browser not showing up

### ISSUE THREAD

**Issue by Termshoo** [mozart/vscode-oz#5]
Hello,
When i use this extension the Oz browser is not showing up.
For example, if i run the code
`{Browse 3}`
nothing will show up besides the feed in the output. Any idea on how to see the `3` somewhere ? 😃

**Comment by layus** [comment]
Well, you would have to test your installation of oz. What happens if you open the vanilla oz editor (aka emacs) with the oz launcher ? Are you able to feed '{Browse 3}' and get the browser ?

This plugin does not install mozart-oz. It uses the system install.

You could also try to '{Show 3}' and see if you get any output in the 'Oz Emulator' buffer (you can switch buffers using the dropdown menu).

**Comment by Termshoo** [comment]
`{Show 3}` is working in VSCode !
Everything is ok on emacs, i get the browser with `Browse`... Don't understand why `Browse` is not working in VS but i'll use `Show` instead.
Thank you for your answer !

**Comment by layus** [comment]
That's weird, because emacs and vscode use the same interface.

I has some issues recently where the last line of input was not fed to th eoz emulator.
Could you feed several {Browse xxx} calls on multiple lines, an see if some get browsed.

Also be warned that the browser window may not appear on top of the others. You may have to "look for it" in the windows stack.

**Comment by Termshoo** [comment]
Well, with multiple lines it worked ! Don't understand why...
(And the window appear on top :)
